builds:
  - id: battery
    main: ./cmd/battery/main.go
    binary: battery
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: arm
        goarm: "7"
      - goos: windows
        goarch: arm
        goarm: "7"

archives:
- builds:
  - battery
  name_template: 'battery_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  files:
  - LICENSE

brews:
- name: battery
  tap:
    owner: Code-Hex
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
  homepage: https://github.com/Code-Hex/battery
  description: Display your battery status on terminal (or tmux) written by Go
  folder: Formula
  install: |
    bin.install "battery"
nfpms:
  - license: MIT License
    maintainer: Kei Kamikawa <x00.x7f.x86@gmail.com>
    homepage: https://github.com/Code-Hex/battery
    bindir: /usr/local/bin
    description: Display your battery status on terminal (or tmux) written by Go
    replacements:
      linux: Linux
    formats:
      - apk
      - deb
      - rpm

checksum:
  name_template: 'battery_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch
